### ISSUE TITLE
de4dot deobfuscate

### ISSUE THREAD

**Issue by cocorico8** [stayintarkov/SIT.Manager#1]
i was wondering if you could re-implant de4dot because it is much faster to pass by that than to get to the CLI and using the one of spt ( i would have done it myself but i don't know much code ( maybe i'll learn it some day ))

**Comment by Lacyway** [comment]
Will eventually add this, but low prio for now.

**Comment by cocorico8** [comment]
of course take your time

**Comment by cocorico8** [comment]
> @cocorico8 this will remain in [SIT.Launcher.Classic](https://github.com/stayintarkov/SIT.Launcher.Classic) for now

sorry didn't saw the message i understand thanks for the consideration
