### ISSUE TITLE
Error 426

### ISSUE THREAD

**Issue by RaidmaxSpace** [stayintarkov/SIT.Manager#10]
![Capture d'écran 2023-12-13 141146](https://github.com/stayintarkov/SIT.Manager/assets/133020878/a4a85eb1-4fa2-4ab5-8fa8-1f6c9b384d92)

Hello, here I have this error, I don't understand why it's telling me this. 

I installed everything as the tuto, namely that I can play locally with port 6969 but not 6970, for time I opened the ports in my internet box and my firewall.

if you have time to help, thank you.

**Comment by Lacyway** [comment]
Unrelated to the manager itself.
