### ISSUE TITLE
Tarkov 0.14

### ISSUE THREAD

**Issue by Xip92** [stayintarkov/SIT.Manager#11]
does the manager work with tarkov update 0.14.0? or wait for an update of the manager.

**Comment by EmmettPeck** [comment]
0.14.0 Does not seem to downgrade to SPT-AKI 13.9

**Comment by Xip92** [comment]
thanks for the reply,
 is there a patcher for downgrading 1.9? With the patcher from spt only works on 13.5

**Comment by grimvx** [comment]
Bump. The AKI Patcher doesn't go from 0.14.0 to 13.9.1 and you can't select an earlier SIT version that works with 13.5.3.

**Comment by Xip92** [comment]
Then I have to wait until the manager is compatible with 0.14.0 at some point.
Thanks

**Comment by Lacyway** [comment]
This is not an error with the manager itself. It fetches the downgraders from SPT but they don't have one for the current SIT version as it is ahead of SPT, resulting in the error message. 

I will look into alternative mirrors hosted by us instead as well.

**Comment by Lacyway** [comment]
> I'll wait until it's compatible at some point. My official tarkov is at 0.14 same as the copy I created for coop
> 
> Tarkov 1.9 is currently only compatible in the manager but you can't downgrade 0.14 to 1.9 unfortunately.
> 
> and nothing works for me with the sit launcher classic. [Feedback geben](https://www.google.com/search?ie=UTF-8&client=ms-android-samsung-rvo1&source=android-browser&q=google+%C3%BCbersetzer#) Andere

You can still downgrade manually using the links on our discord.

**Comment by Xip92** [comment]
Okay, thank you for the information
I'll try it this evening.
