### ISSUE TITLE
Installation procedures

### ISSUE THREAD

**Issue by jpeckham** [stayintarkov/SIT.Manager#21]
Hi team! Really excited about your project and I would love to try to use it. I'm having a bit of confusion in the installation steps and usage of this application that I hope could get improved into the wiki:

so i've followed the steps to download the manager. Once you run the exe, what happens next? it's unclear... but i did try to 'explore on my own'. I tried to select my "EFT" folder... i wondered... should i select my regular EFT folder? or perhaps i should copy it first. So, I copied it first to a new location.

Then I presume i should select the AKI folder. Well i had run the AKI installer which installed 3.7.6 into D:\spt\3.7.6 SIT\

Then i chose to 'install sit'. This is where i got lost because the only options to select for SIT were versions 13.9.* which are not compatible with any released version of SPT let alone 3.7.6 which uses 13.5.3.26535.

So that's where i am lost and stuck.

I tried to use the instructions and the intuitive user interface but hoping the documentation could be beefed up with some assistance.

Thanks!

**Comment by Plootie** [comment]
SIT 13.9.* should be compatible with SPT 3.7.6. In case you haven't already you will need to downgrade your EFT from 0.14 until SPT and SIT update to 0.14 which is in the works but not complete yet

**Comment by jpeckham** [comment]
thank you. i greatly appreciate your time and your response. I can confirm that i am on  SPT 3.7.6 which uses EFT downgraded to 13.5.3.26535 which is all in 1 folder (D:\SPTarkov\SPT  SIT) and operates fine stand alone without SIT installed. When i run SIT manager (latest release under releases "1.1.8742.38089") and configure and try to install SIT i get an error. "unable to downgrade". I tried both the live BSG/EFT folder and the folder that had my downgraded EFT client for SPT 3.7.6.

for clarity can you confirm the detailed steps of what you claim is the procedure?

to help illustrate where i probably have gone wrong, here is what i think i hear you saying and what i did:

- download the spt installer into a folder ("D:\SPTarkov\SPT  SIT" is what i used)
- run spt installer
- achieve 3.7.6 (in "D:\SPTarkov\SPT  SIT" mentioned above)
- download sit manager from latest releases and unzip (i put in d:\spt\sit manager)
- run sit.manager exe
- in sit manager - settings -> eft path: configure EFT folder to where i have the appropriate 3.7.6 client files ( "D:\SPTarkov\SPT  SIT") (i also tried "C:\Battlestate Games\Escape from Tarkov" but that corrupted my live game and i had to reinstall tarkov)
- in sit manager - settings -> spt-aki path: configure the SPT folder to the SPT folder (also "D:\SPTarkov\SPT  SIT")
- in sit manager - tools install sit (sit.client 1.9.8766.40295 tarkov version 0.13.9.1.27622 <- note that is too high for SPT): click the 'install sit' button, choose the latest sit

that is when i got the error paraphrasing: "Downgrade error escape fromt arkov cannot be downgraded to the version required...."

i also tried installing all the other sit client versions. all same error.

**Comment by jpeckham** [comment]
i tried something a little different. i put a copy of latest greatest EFT into 
`D:\SPTarkov\Client 0.14.0.1.28476` then copied it to `D:\SPTarkov\Client 0.14.0.1.28476 - Copy` and configured the eft path to that
then copied SPT 3.7.6 to `D:\SPTarkov\SPT 3.7.6` - Copy since i kept corrupting that.


![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/c50949ae-a4de-420b-a992-21948b34ef77)

installed sit
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/647019fd-435e-4308-aa2b-135cada12dfa)

which. seemed to exec with no error (no confirmation per say)
start server works
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/5a3f99be-d9ce-41b2-a5af-0f4afe446681)

but play does not
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/d5a005bc-b07f-4db8-a40a-be9d13d531ae)

**Comment by jpeckham** [comment]
found client instructions here https://github.com/stayintarkov/StayInTarkov.Client?tab=readme-ov-file#sit-manager-method
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/27398646-8a4c-4889-99b9-cfd704204eb8)

and repeated the process to use manager as described with the 'corrected' folder structure.
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/e05e2cbb-26d9-451d-8f34-14f4503f16bc)

same error:
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/968ebced-b4b2-410c-85fc-2a6910569489)

 note: this selection box to install SIT
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/b3e8a3de-66c9-4e49-b381-48503127b5e1)

 appears to want the EFT version of 13.9.1.27622. there is no SPT downgrader that can go from 14.* to this EFT version. are we just waiting on some releases of tools perhaps?

**Comment by jpeckham** [comment]
ok best i can tell, because latest manager can't downgrade 14*, you have to sort of mix and match some installer with manual steps.

1. run 3.7.6 spt installer in \sit\server
2. copy latest battlestate/eft into \sit\game and run downgrader on it
3. copy latest release of manager into \sit\launcher
4. manually put sit server mod 'SITCoop' folder into \sit\server\user\mods\

Then sit.manager will work to install SIT on the client in \sit\game

trying 'that' :
![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/85188fd7-10bb-4943-a951-3145dd9d6042)

still fails with not downgradable error. Again i suspect that it wants EFT 13.9 which isn't seemingly achievable.

![image](https://github.com/stayintarkov/SIT.Manager/assets/65101/51bd9e41-a971-4f40-a981-f34c1f480cd4)

just does not seem to work with EFT 13.5 (latest greatest downgrader???)

**Comment by Plootie** [comment]
I'll be honest i have only had to do the installation once and on 13.9 so i'm not too familiar with the installation but if the manager isn't able to downgrade 0.14 there is [this](https://pixeldrain.com/u/kjyCE4Ly) downgrader from the SIT discord that might work for you

**Comment by jpeckham** [comment]
@Plootie  thanks i'm trying that out but it sure sounds like exactly what i need by my very first observation of EFT being 14.0 and SPT being 13.5.

**Comment by Plootie** [comment]
Decided to have a quick check at why the manager was failing to downgrade for you. The manager pulls its downgraders from [here](https://dev.sp-tarkov.com/SPT-AKI/Downgrade-Patches/releases) which appears to only host downgraders to downgrade to 0.13.9.1.26535 but SIT wanted 13.9.1.27622 which is what the downgrader from the discord does. I'm not certain where trippy gets the downpatchers for the discord from but the only solutions I can see to resolve this would be to either wait for the downpatcher repo to post some downpatchers for the later version of EFT or to upload the new patchers to another place and have the manager pull from there (not a fan of this idea). I'll make some pull requests to change the install instructions for now to let people know how to work around this until its resolved

**Comment by mihaicm93** [comment]
https://github.com/stayintarkov/SIT.Manager/pull/22 should fix the issue with downgrade patchers
