### ISSUE TITLE
Can't launch SIT.Manager.exe

### ISSUE THREAD

**Issue by Simonrak** [stayintarkov/SIT.Manager#3]
Can't run the .exe, launcher.log is empty.

Event Viewer:

Faulting application name: SIT.Manager.exe, version: 1.1.8726.26644, time stamp: 0x65310000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.4.0, time stamp: 0x49d9bb27
Exception code: 0xc000027b
Fault offset: 0x00000000003b78a4
Faulting process id: 0x0x7124
Faulting application start time: 0x0x1DA1DA2BCC9884F
Faulting application path: D:\SIT\launcher\SIT.Manager.exe
Faulting module path: D:\SIT\launcher\Microsoft.ui.xaml.dll
Report Id: b990b9a2-f8c3-4b67-b82b-1edc15cbfdb5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Lacyway** [comment]
Done a lot of changes to the boot of the App, should hopefully work now.

**Comment by Simonrak** [comment]
> Done a lot of changes to the boot of the App, should hopefully work now.

That fixed it, great job!
